In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/DBDA_PROJECT/Total.csv")

In [ ]:
df

,class,accuraccy,precision,recall,f1,support,model
0,0,100.000000,0.993617,1.000000,0.996798,467,balanced_SMOTE_CNN.csv
1,1,94.004796,0.990123,0.961631,0.975669,417,balanced_SMOTE_CNN.csv
2,2,100.000000,0.993521,0.995671,0.994595,462,balanced_SMOTE_CNN.csv
3,3,98.623853,0.995402,0.993119,0.994259,436,balanced_SMOTE_CNN.csv
4,4,99.782135,1.000000,1.000000,1.000000,459,balanced_SMOTE_CNN.csv
...,...,...,...,...,...,...,...
511,38,97.849462,0.918635,0.940860,0.929615,372,imbalanced_RESNET_152.csv
512,39,100.000000,0.914894,0.977273,0.945055,88,imbalanced_RESNET_152.csv
513,40,87.577640,0.949405,0.990683,0.969605,322,imbalanced_RESNET_152.csv
514,41,95.925926,0.931900,0.962963,0.947177,270,imbalanced_RESNET_152.csv
515,42,98.571429,0.982332,0.992857,0.987567,280,imbalanced_RESNET_152.csv

In [ ]:
df['total'] = df['accuraccy']+df['precision'] + df['recall'] + df['f1']

In [ ]:
df.total = df.total.round(4)

In [ ]:
df.groupby('class',sort=False)['total'].max()

class
0     103.0000
1     101.4107
2     102.9966
3     102.9320
4     103.0000
5     103.0000
6     103.0000
7     102.9874
8     103.0000
9     103.0000
10    102.9394
11    103.0000
12    102.5297
13    102.4582
14    102.9809
15    103.0000
16    102.9876
17    103.0000
18    102.9717
19    102.7836
20    102.9966
21    103.0000
22    102.9894
23    102.9535
24    102.9938
25    102.9800
26    103.0000
27    103.0000
28    103.0000
29    103.0000
30    103.0000
31    103.0000
32    103.0000
33    103.0000
34    102.9849
35    103.0000
36    103.0000
37    103.0000
38    102.9154
39    103.0000
40    102.5217
41    102.8630
42    102.9935
Name: total, dtype: float64

In [ ]:
df0=df[(df['class']==0) & (df['total']==df['total'].max())].iloc[:,0:7]
df0

,class,accuraccy,precision,recall,f1,support,model
301,0,100.0,1.0,1.0,1.0,36,balanced_wt_ResNet_50.csv

In [ ]:
# df1=df[(df['class']==1) & (df['total']==z[1].max())].iloc[:,0:8]
# df1

In [ ]:
df1=df[(df['class']==1) & (df['total']==101.4107)].iloc[:,0:7]
df1

,class,accuraccy,precision,recall,f1,support,model
173,1,98.526316,0.952479,0.970526,0.961418,475,balanced_tk_ResNet50_50.csv

In [ ]:
df2=df[(df['class']==2) & (df['total']==102.9966)].iloc[:,0:7]
df2

,class,accuraccy,precision,recall,f1,support,model
432,2,100.0,0.997727,1.0,0.998862,439,imbalanced_resnet_L50.csv

In [ ]:
df3=df[(df['class']==3) & (df['total']==102.9320)].iloc[:,0:7]
df3

,class,accuraccy,precision,recall,f1,support,model
175,3,100.0,0.958801,0.996109,0.977099,257,balanced_tk_ResNet50_50.csv

In [ ]:
df4=df[(df['class']==4) & (df['total']==df['total'].max())].iloc[:,0:7]
df4

,class,accuraccy,precision,recall,f1,support,model
305,4,100.0,1.0,1.0,1.0,421,balanced_wt_ResNet_50.csv
434,4,100.0,1.0,1.0,1.0,421,imbalanced_resnet_L50.csv

In [ ]:
df5=df[(df['class']==5) & (df['total']==df['total'].max())].iloc[:,0:7]
df5

,class,accuraccy,precision,recall,f1,support,model
306,5,100.0,1.0,1.0,1.0,432,balanced_wt_ResNet_50.csv

In [ ]:
df6=df[(df['class']==6) & (df['total']==df['total'].max())].iloc[:,0:7]
df6

,class,accuraccy,precision,recall,f1,support,model
92,6,100.0,1.0,1.0,1.0,475,balanced_SMOTE_ResNet_152.csv
135,6,100.0,1.0,1.0,1.0,169,balanced_tk_cnn.csv
221,6,100.0,1.0,1.0,1.0,169,balanced_tk_ResNet50_152.csv
307,6,100.0,1.0,1.0,1.0,162,balanced_wt_ResNet_50.csv
393,6,100.0,1.0,1.0,1.0,162,imbalanced_cnn.csv

In [ ]:
df7=df[(df['class']==7) & (df['total']==102.9874)].iloc[:,0:7]
df7

,class,accuraccy,precision,recall,f1,support,model
136,7,100.0,1.0,0.991597,0.995781,119,balanced_tk_cnn.csv

In [ ]:
df8=df[(df['class']==8) & (df['total']==df['total'].max())].iloc[:,0:7]
df8

,class,accuraccy,precision,recall,f1,support,model
8,8,100.0,1.0,1.0,1.0,467,balanced_SMOTE_CNN.csv
223,8,100.0,1.0,1.0,1.0,88,balanced_tk_ResNet50_152.csv
309,8,100.0,1.0,1.0,1.0,81,balanced_wt_ResNet_50.csv
438,8,100.0,1.0,1.0,1.0,81,imbalanced_resnet_L50.csv

In [ ]:
df9=df[(df['class']==9) & (df['total']==df['total'].max())].iloc[:,0:7]
df9

,class,accuraccy,precision,recall,f1,support,model
138,9,100.0,1.0,1.0,1.0,241,balanced_tk_cnn.csv
310,9,100.0,1.0,1.0,1.0,227,balanced_wt_ResNet_50.csv
396,9,100.0,1.0,1.0,1.0,227,imbalanced_cnn.csv

In [ ]:
df10=df[(df['class']==10) & (df['total']==102.9394)].iloc[:,0:7]
df10

,class,accuraccy,precision,recall,f1,support,model
182,10,100.0,0.987755,0.971888,0.979757,249,balanced_tk_ResNet50_50.csv

In [ ]:
df11=df[(df['class']==11) & (df['total']==df['total'].max())].iloc[:,0:7]
df11

     class  accuraccy  precision  recall   f1  support                model
140     11      100.0        1.0     1.0  1.0       34  balanced_tk_cnn.csv

In [ ]:
df12=df[(df['class']==12) & (df['total']==102.5297)].iloc[:,0:7]
df12

,class,accuraccy,precision,recall,f1,support,model
313,12,99.559471,0.99117,0.988987,0.990077,454,balanced_wt_ResNet_50.csv

In [ ]:
df13=df[(df['class']==13) & (df['total']==102.4582)].iloc[:,0:7]
df13

,class,accuraccy,precision,recall,f1,support,model
56,13,99.529412,0.997543,0.955294,0.975962,425,balanced_SMOTE_ResNet_50.csv

In [ ]:
df14=df[(df['class']==14) & (df['total']==102.9809)].iloc[:,0:7]
df14

,class,accuraccy,precision,recall,f1,support,model
100,14,100.0,0.987288,1.0,0.993603,466,balanced_SMOTE_ResNet_152.csv

In [ ]:
df15=df[(df['class']==15) & (df['total']==df['total'].max())].iloc[:,0:7]
df15

,class,accuraccy,precision,recall,f1,support,model
58,15,100.0,1.0,1.0,1.0,449,balanced_SMOTE_ResNet_50.csv
101,15,100.0,1.0,1.0,1.0,449,balanced_SMOTE_ResNet_152.csv
316,15,100.0,1.0,1.0,1.0,82,balanced_wt_ResNet_50.csv
402,15,100.0,1.0,1.0,1.0,82,imbalanced_cnn.csv
445,15,100.0,1.0,1.0,1.0,82,imbalanced_resnet_L50.csv

In [ ]:
df16=df[(df['class']==16) & (df['total']==102.9876)].iloc[:,0:7]
df16

,class,accuraccy,precision,recall,f1,support,model
16,16,100.0,0.995868,0.995868,0.995868,484,balanced_SMOTE_CNN.csv

In [ ]:
df17=df[(df['class']==17) & (df['total']==df['total'].max())].iloc[:,0:7]
df17

,class,accuraccy,precision,recall,f1,support,model
318,17,100.0,1.0,1.0,1.0,53,balanced_wt_ResNet_50.csv

In [ ]:
df18=df[(df['class']==18) & (df['total']==102.9717)].iloc[:,0:7]
df18

,class,accuraccy,precision,recall,f1,support,model
147,18,100.0,0.996198,0.984962,0.990548,266,balanced_tk_cnn.csv

In [ ]:
df19=df[(df['class']==19) & (df['total']==102.7836)].iloc[:,0:7]
df19

,class,accuraccy,precision,recall,f1,support,model
62,19,100.0,0.992683,0.865957,0.925,470,balanced_SMOTE_ResNet_50.csv

In [ ]:
df20=df[(df['class']==20) & (df['total']==102.9966)].iloc[:,0:7]
df20

,class,accuraccy,precision,recall,f1,support,model
20,20,100.0,0.997701,1.0,0.998849,434,balanced_SMOTE_CNN.csv

In [ ]:
df21=df[(df['class']==21) & (df['total']==df['total'].max())].iloc[:,0:7]
df21

,class,accuraccy,precision,recall,f1,support,model
322,21,100.0,1.0,1.0,1.0,100,balanced_wt_ResNet_50.csv
408,21,100.0,1.0,1.0,1.0,100,imbalanced_cnn.csv

In [ ]:
df22=df[(df['class']==22) & (df['total']==102.9894)].iloc[:,0:7]
df22

,class,accuraccy,precision,recall,f1,support,model
65,22,100.0,0.997642,0.995294,0.996466,425,balanced_SMOTE_ResNet_50.csv

In [ ]:
df23=df[(df['class']==23) & (df['total']==102.9535)].iloc[:,0:7]
df23

,class,accuraccy,precision,recall,f1,support,model
23,23,100.0,0.973568,0.995495,0.98441,444,balanced_SMOTE_CNN.csv

In [ ]:
df24=df[(df['class']==24) & (df['total']==102.9938)].iloc[:,0:7]
df24

,class,accuraccy,precision,recall,f1,support,model
24,24,100.0,1.0,0.995876,0.997934,485,balanced_SMOTE_CNN.csv

In [ ]:
df25=df[(df['class']==25) & (df['total']==102.9800)].iloc[:,0:7]
df25

,class,accuraccy,precision,recall,f1,support,model
25,25,100.0,0.988938,0.997768,0.993333,448,balanced_SMOTE_CNN.csv

In [ ]:
df26=df[(df['class']==26) & (df['total']==df['total'].max())].iloc[:,0:7]
df26

,class,accuraccy,precision,recall,f1,support,model
26,26,100.0,1.0,1.0,1.0,442,balanced_SMOTE_CNN.csv
69,26,100.0,1.0,1.0,1.0,442,balanced_SMOTE_ResNet_50.csv
327,26,100.0,1.0,1.0,1.0,40,balanced_wt_ResNet_50.csv
413,26,100.0,1.0,1.0,1.0,40,imbalanced_cnn.csv
456,26,100.0,1.0,1.0,1.0,40,imbalanced_resnet_L50.csv

In [ ]:
df27=df[(df['class']==27) & (df['total']==df['total'].max())].iloc[:,0:7]
df27

,class,accuraccy,precision,recall,f1,support,model
199,27,100.0,1.0,1.0,1.0,153,balanced_tk_ResNet50_50.csv
328,27,100.0,1.0,1.0,1.0,137,balanced_wt_ResNet_50.csv
414,27,100.0,1.0,1.0,1.0,137,imbalanced_cnn.csv

In [ ]:
df28=df[(df['class']==28) & (df['total']==df['total'].max())].iloc[:,0:7]
df28

,class,accuraccy,precision,recall,f1,support,model
286,28,100.0,1.0,1.0,1.0,83,balanced_WT_cnn.csv
329,28,100.0,1.0,1.0,1.0,83,balanced_wt_ResNet_50.csv
458,28,100.0,1.0,1.0,1.0,83,imbalanced_resnet_L50.csv
501,28,100.0,1.0,1.0,1.0,83,imbalanced_RESNET_152.csv

In [ ]:
df29=df[(df['class']==29) & (df['total']==df['total'].max())].iloc[:,0:7]
df29

,class,accuraccy,precision,recall,f1,support,model
29,29,100.0,1.0,1.0,1.0,480,balanced_SMOTE_CNN.csv
330,29,100.0,1.0,1.0,1.0,222,balanced_wt_ResNet_50.csv

In [ ]:
df30=df[(df['class']==30) & (df['total']==df['total'].max())].iloc[:,0:7]
df30

,class,accuraccy,precision,recall,f1,support,model
30,30,100.0,1.0,1.0,1.0,441,balanced_SMOTE_CNN.csv
331,30,100.0,1.0,1.0,1.0,62,balanced_wt_ResNet_50.csv
417,30,100.0,1.0,1.0,1.0,62,imbalanced_cnn.csv
460,30,100.0,1.0,1.0,1.0,62,imbalanced_resnet_L50.csv
503,30,100.0,1.0,1.0,1.0,62,imbalanced_RESNET_152.csv

In [ ]:
df31=df[(df['class']==31) & (df['total']==df['total'].max())].iloc[:,0:7]
df31

,class,accuraccy,precision,recall,f1,support,model
117,31,100.0,1.0,1.0,1.0,456,balanced_SMOTE_ResNet_152.csv
160,31,100.0,1.0,1.0,1.0,42,balanced_tk_cnn.csv
203,31,100.0,1.0,1.0,1.0,42,balanced_tk_ResNet50_50.csv
246,31,100.0,1.0,1.0,1.0,42,balanced_tk_ResNet50_152.csv
289,31,100.0,1.0,1.0,1.0,47,balanced_WT_cnn.csv
332,31,100.0,1.0,1.0,1.0,47,balanced_wt_ResNet_50.csv
418,31,100.0,1.0,1.0,1.0,47,imbalanced_cnn.csv
504,31,100.0,1.0,1.0,1.0,47,imbalanced_RESNET_152.csv

In [ ]:
df32=df[(df['class']==32) & (df['total']==df['total'].max())].iloc[:,0:7]
df32

,class,accuraccy,precision,recall,f1,support,model
32,32,100.0,1.0,1.0,1.0,458,balanced_SMOTE_CNN.csv
333,32,100.0,1.0,1.0,1.0,399,balanced_wt_ResNet_50.csv

In [ ]:
df33=df[(df['class']==33) & (df['total']==df['total'].max())].iloc[:,0:7]
df33

,class,accuraccy,precision,recall,f1,support,model
76,33,100.0,1.0,1.0,1.0,471,balanced_SMOTE_ResNet_50.csv
162,33,100.0,1.0,1.0,1.0,56,balanced_tk_cnn.csv
205,33,100.0,1.0,1.0,1.0,56,balanced_tk_ResNet50_50.csv
291,33,100.0,1.0,1.0,1.0,68,balanced_WT_cnn.csv
334,33,100.0,1.0,1.0,1.0,68,balanced_wt_ResNet_50.csv
463,33,100.0,1.0,1.0,1.0,68,imbalanced_resnet_L50.csv

In [ ]:
df34=df[(df['class']==34) & (df['total']==102.9849)].iloc[:,0:7]
df34

,class,accuraccy,precision,recall,f1,support,model
335,34,100.0,0.992443,0.997468,0.994949,395,balanced_wt_ResNet_50.csv

In [ ]:
df35=df[(df['class']==35) & (df['total']==df['total'].max())].iloc[:,0:7]
df35

,class,accuraccy,precision,recall,f1,support,model
121,35,100.0,1.0,1.0,1.0,420,balanced_SMOTE_ResNet_152.csv
336,35,100.0,1.0,1.0,1.0,79,balanced_wt_ResNet_50.csv

In [ ]:
df36=df[(df['class']==36) & (df['total']==df['total'].max())].iloc[:,0:7]
df36

,class,accuraccy,precision,recall,f1,support,model
208,36,100.0,1.0,1.0,1.0,43,balanced_tk_ResNet50_50.csv
337,36,100.0,1.0,1.0,1.0,49,balanced_wt_ResNet_50.csv
423,36,100.0,1.0,1.0,1.0,49,imbalanced_cnn.csv
466,36,100.0,1.0,1.0,1.0,49,imbalanced_resnet_L50.csv

In [ ]:
df37=df[(df['class']==37) & (df['total']==df['total'].max())].iloc[:,0:7]
df37

,class,accuraccy,precision,recall,f1,support,model
295,37,100.0,1.0,1.0,1.0,44,balanced_WT_cnn.csv
338,37,100.0,1.0,1.0,1.0,44,balanced_wt_ResNet_50.csv
424,37,100.0,1.0,1.0,1.0,44,imbalanced_cnn.csv
467,37,100.0,1.0,1.0,1.0,44,imbalanced_resnet_L50.csv

In [ ]:
df38=df[(df['class']==38) & (df['total']==102.9154)].iloc[:,0:7]
df38

,class,accuraccy,precision,recall,f1,support,model
38,38,100.0,0.993007,0.950893,0.971494,448,balanced_SMOTE_CNN.csv

In [ ]:
df39=df[(df['class']==39) & (df['total']==df['total'].max())].iloc[:,0:7]
df39

,class,accuraccy,precision,recall,f1,support,model
125,39,100.0,1.0,1.0,1.0,416,balanced_SMOTE_ResNet_152.csv
297,39,100.0,1.0,1.0,1.0,88,balanced_WT_cnn.csv
340,39,100.0,1.0,1.0,1.0,88,balanced_wt_ResNet_50.csv
426,39,100.0,1.0,1.0,1.0,88,imbalanced_cnn.csv

In [ ]:
df40=df[(df['class']==40) & (df['total']==102.5217)].iloc[:,0:7]
df40

,class,accuraccy,precision,recall,f1,support,model
126,40,99.56427,0.9869,0.984749,0.985823,459,balanced_SMOTE_ResNet_152.csv

In [ ]:
df41=df[(df['class']==41) & (df['total']==102.8630)].iloc[:,0:7]
df41

,class,accuraccy,precision,recall,f1,support,model
213,41,100.0,0.968992,0.93985,0.954198,266,balanced_tk_ResNet50_50.csv

In [ ]:
df42=df[(df['class']==42) & (df['total']==102.9935)].iloc[:,0:7]
df42

,class,accuraccy,precision,recall,f1,support,model
85,42,100.0,0.99568,1.0,0.997835,461,balanced_SMOTE_ResNet_50.csv

In [ ]:
df_list=[df,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23,df24,df25,df26,df27,df28,df29,df30,df31,df32,df33,df34,df35,df36,df37,df38,df39,df40,df41,df42]

In [ ]:
model_df=pd.concat([df0,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23,df24,df25,df26,df27,df28,df29,df30,df31,df32,df33,df34,df35,df36,df37,df38,df39,df40,df41,df42], sort=False)

In [ ]:
model_df

,class,accuraccy,precision,recall,f1,support,model
301,0,100.000000,1.000000,1.000000,1.000000,36,balanced_wt_ResNet_50.csv
173,1,98.526316,0.952479,0.970526,0.961418,475,balanced_tk_ResNet50_50.csv
432,2,100.000000,0.997727,1.000000,0.998862,439,imbalanced_resnet_L50.csv
175,3,100.000000,0.958801,0.996109,0.977099,257,balanced_tk_ResNet50_50.csv
305,4,100.000000,1.000000,1.000000,1.000000,421,balanced_wt_ResNet_50.csv
...,...,...,...,...,...,...,...
340,39,100.000000,1.000000,1.000000,1.000000,88,balanced_wt_ResNet_50.csv
426,39,100.000000,1.000000,1.000000,1.000000,88,imbalanced_cnn.csv
126,40,99.564270,0.986900,0.984749,0.985823,459,balanced_SMOTE_ResNet_152.csv
213,41,100.000000,0.968992,0.939850,0.954198,266,balanced_tk_ResNet50_50.csv
85,42,100.000000,0.995680,1.000000,0.997835,461,balanced_SMOTE_ResNet_50.csv

In [ ]:
print(model_df.to_string())

     class   accuraccy  precision    recall        f1  support                          model
301      0  100.000000   1.000000  1.000000  1.000000       36      balanced_wt_ResNet_50.csv
173      1   98.526316   0.952479  0.970526  0.961418      475    balanced_tk_ResNet50_50.csv
432      2  100.000000   0.997727  1.000000  0.998862      439      imbalanced_resnet_L50.csv
175      3  100.000000   0.958801  0.996109  0.977099      257    balanced_tk_ResNet50_50.csv
305      4  100.000000   1.000000  1.000000  1.000000      421      balanced_wt_ResNet_50.csv
434      4  100.000000   1.000000  1.000000  1.000000      421      imbalanced_resnet_L50.csv
306      5  100.000000   1.000000  1.000000  1.000000      432      balanced_wt_ResNet_50.csv
92       6  100.000000   1.000000  1.000000  1.000000      475  balanced_SMOTE_ResNet_152.csv
135      6  100.000000   1.000000  1.000000  1.000000      169            balanced_tk_cnn.csv
221      6  100.000000   1.000000  1.000000  1.000000      169   balanced_tk_ResNet50_152.csv
307      6  100.000000   1.000000  1.000000  1.000000      162      balanced_wt_ResNet_50.csv
393      6  100.000000   1.000000  1.000000  1.000000      162             imbalanced_cnn.csv
136      7  100.000000   1.000000  0.991597  0.995781      119            balanced_tk_cnn.csv
8        8  100.000000   1.000000  1.000000  1.000000      467         balanced_SMOTE_CNN.csv
223      8  100.000000   1.000000  1.000000  1.000000       88   balanced_tk_ResNet50_152.csv
309      8  100.000000   1.000000  1.000000  1.000000       81      balanced_wt_ResNet_50.csv
438      8  100.000000   1.000000  1.000000  1.000000       81      imbalanced_resnet_L50.csv
138      9  100.000000   1.000000  1.000000  1.000000      241            balanced_tk_cnn.csv
310      9  100.000000   1.000000  1.000000  1.000000      227      balanced_wt_ResNet_50.csv
396      9  100.000000   1.000000  1.000000  1.000000      227             imbalanced_cnn.csv
182     10  100.000000   0.987755  0.971888  0.979757      249    balanced_tk_ResNet50_50.csv
140     11  100.000000   1.000000  1.000000  1.000000       34            balanced_tk_cnn.csv
313     12   99.559471   0.991170  0.988987  0.990077      454      balanced_wt_ResNet_50.csv
56      13   99.529412   0.997543  0.955294  0.975962      425   balanced_SMOTE_ResNet_50.csv
100     14  100.000000   0.987288  1.000000  0.993603      466  balanced_SMOTE_ResNet_152.csv
58      15  100.000000   1.000000  1.000000  1.000000      449   balanced_SMOTE_ResNet_50.csv
101     15  100.000000   1.000000  1.000000  1.000000      449  balanced_SMOTE_ResNet_152.csv
316     15  100.000000   1.000000  1.000000  1.000000       82      balanced_wt_ResNet_50.csv
402     15  100.000000   1.000000  1.000000  1.000000       82             imbalanced_cnn.csv
445     15  100.000000   1.000000  1.000000  1.000000       82      imbalanced_resnet_L50.csv
16      16  100.000000   0.995868  0.995868  0.995868      484         balanced_SMOTE_CNN.csv
318     17  100.000000   1.000000  1.000000  1.000000       53      balanced_wt_ResNet_50.csv
147     18  100.000000   0.996198  0.984962  0.990548      266            balanced_tk_cnn.csv
62      19  100.000000   0.992683  0.865957  0.925000      470   balanced_SMOTE_ResNet_50.csv
20      20  100.000000   0.997701  1.000000  0.998849      434         balanced_SMOTE_CNN.csv
322     21  100.000000   1.000000  1.000000  1.000000      100      balanced_wt_ResNet_50.csv
408     21  100.000000   1.000000  1.000000  1.000000      100             imbalanced_cnn.csv
65      22  100.000000   0.997642  0.995294  0.996466      425   balanced_SMOTE_ResNet_50.csv
23      23  100.000000   0.973568  0.995495  0.984410      444         balanced_SMOTE_CNN.csv
24      24  100.000000   1.000000  0.995876  0.997934      485         balanced_SMOTE_CNN.csv
25      25  100.000000   0.988938  0.997768  0.993333      448         balanced_SMOTE_CNN.csv
26      26  100.000000   1.000000  1.000000  1.000000      442         balanced_SMOTE_CNN.csv
69      26  100.000000   1.000000  1.000000  1.000000      442   balanced_SMOTE_ResNet_50.csv
327     26  100.000000   1.000000  1.000000  1.000000       40      balanced_wt_ResNet_50.csv
413     26  100.000000   1.000000  1.000000  1.000000       40             imbalanced_cnn.csv
456     26  100.000000   1.000000  1.000000  1.000000       40      imbalanced_resnet_L50.csv
199     27  100.000000   1.000000  1.000000  1.000000      153    balanced_tk_ResNet50_50.csv
328     27  100.000000   1.000000  1.000000  1.000000      137      balanced_wt_ResNet_50.csv
414     27  100.000000   1.000000  1.000000  1.000000      137             imbalanced_cnn.csv
286     28  100.000000   1.000000  1.000000  1.000000       83            balanced_WT_cnn.csv
329     28  100.000000   1.000000  1.000000  1.000000       83      balanced_wt_ResNet_50.csv
458     28  100.000000   1.000000  1.000000  1.000000       83      imbalanced_resnet_L50.csv
501     28  100.000000   1.000000  1.000000  1.000000       83      imbalanced_RESNET_152.csv
29      29  100.000000   1.000000  1.000000  1.000000      480         balanced_SMOTE_CNN.csv
330     29  100.000000   1.000000  1.000000  1.000000      222      balanced_wt_ResNet_50.csv
30      30  100.000000   1.000000  1.000000  1.000000      441         balanced_SMOTE_CNN.csv
331     30  100.000000   1.000000  1.000000  1.000000       62      balanced_wt_ResNet_50.csv
417     30  100.000000   1.000000  1.000000  1.000000       62             imbalanced_cnn.csv
460     30  100.000000   1.000000  1.000000  1.000000       62      imbalanced_resnet_L50.csv
503     30  100.000000   1.000000  1.000000  1.000000       62      imbalanced_RESNET_152.csv
117     31  100.000000   1.000000  1.000000  1.000000      456  balanced_SMOTE_ResNet_152.csv
160     31  100.000000   1.000000  1.000000  1.000000       42            balanced_tk_cnn.csv
203     31  100.000000   1.000000  1.000000  1.000000       42    balanced_tk_ResNet50_50.csv
246     31  100.000000   1.000000  1.000000  1.000000       42   balanced_tk_ResNet50_152.csv
289     31  100.000000   1.000000  1.000000  1.000000       47            balanced_WT_cnn.csv
332     31  100.000000   1.000000  1.000000  1.000000       47      balanced_wt_ResNet_50.csv
418     31  100.000000   1.000000  1.000000  1.000000       47             imbalanced_cnn.csv
504     31  100.000000   1.000000  1.000000  1.000000       47      imbalanced_RESNET_152.csv
32      32  100.000000   1.000000  1.000000  1.000000      458         balanced_SMOTE_CNN.csv
333     32  100.000000   1.000000  1.000000  1.000000      399      balanced_wt_ResNet_50.csv
76      33  100.000000   1.000000  1.000000  1.000000      471   balanced_SMOTE_ResNet_50.csv
162     33  100.000000   1.000000  1.000000  1.000000       56            balanced_tk_cnn.csv
205     33  100.000000   1.000000  1.000000  1.000000       56    balanced_tk_ResNet50_50.csv
291     33  100.000000   1.000000  1.000000  1.000000       68            balanced_WT_cnn.csv
334     33  100.000000   1.000000  1.000000  1.000000       68      balanced_wt_ResNet_50.csv
463     33  100.000000   1.000000  1.000000  1.000000       68      imbalanced_resnet_L50.csv
335     34  100.000000   0.992443  0.997468  0.994949      395      balanced_wt_ResNet_50.csv
121     35  100.000000   1.000000  1.000000  1.000000      420  balanced_SMOTE_ResNet_152.csv
336     35  100.000000   1.000000  1.000000  1.000000       79      balanced_wt_ResNet_50.csv
208     36  100.000000   1.000000  1.000000  1.000000       43    balanced_tk_ResNet50_50.csv
337     36  100.000000   1.000000  1.000000  1.000000       49      balanced_wt_ResNet_50.csv
423     36  100.000000   1.000000  1.000000  1.000000       49             imbalanced_cnn.csv
466     36  100.000000   1.000000  1.000000  1.000000       49      imbalanced_resnet_L50.csv
295     37  100.000000   1.000000  1.000000  1.000000       44            balanced_WT_cnn.csv
338     37  100.000000   1.000000  1.000000  1.000000       44      balanced_wt_ResNet_50.csv
424     37  100.000000   1.000000  1.000000  1.000000       44             imbalanced_cnn.csv
467     37  100.000000   1.000000  1.000000  1.000000       44      imbalanced_resnet_L50.csv
38      38  100.000000   0.993007  0.950893  0.971494      448         balanced_SMOTE_CNN.csv
125     39  100.000000   1.000000  1.000000  1.000000      416  balanced_SMOTE_ResNet_152.csv
297     39  100.000000   1.000000  1.000000  1.000000       88            balanced_WT_cnn.csv
340     39  100.000000   1.000000  1.000000  1.000000       88      balanced_wt_ResNet_50.csv
426     39  100.000000   1.000000  1.000000  1.000000       88             imbalanced_cnn.csv
126     40   99.564270   0.986900  0.984749  0.985823      459  balanced_SMOTE_ResNet_152.csv
213     41  100.000000   0.968992  0.939850  0.954198      266    balanced_tk_ResNet50_50.csv
85      42  100.000000   0.995680  1.000000  0.997835      461   balanced_SMOTE_ResNet_50.csv

In [ ]:
model_df.model.value_counts()

balanced_wt_ResNet_50.csv        23
imbalanced_cnn.csv               11
balanced_SMOTE_CNN.csv           11
imbalanced_resnet_L50.csv        10
balanced_tk_ResNet50_50.csv       8
balanced_SMOTE_ResNet_152.csv     7
balanced_tk_cnn.csv               7
balanced_SMOTE_ResNet_50.csv      7
balanced_WT_cnn.csv               5
balanced_tk_ResNet50_152.csv      3
imbalanced_RESNET_152.csv         3
Name: model, dtype: int64