In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
import glob
path='/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/'
all_files=glob.glob(path+"*.csv")

In [ ]:
all_files

['/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_SMOTE_CNN.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_SMOTE_ResNet_50.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_SMOTE_ResNet_152.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_tk_cnn.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_tk_ResNet50_50.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_tk_ResNet50_152.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_wt_ResNet_50.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_wt_ResNet_152.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/imbalanced_cnn.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/balanced_WT_cnn.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/imbalanced_RESNET_152.csv',
 '/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/imbalanced_resnet_L50.csv']

In [ ]:
df = pd.DataFrame()
for file_ in all_files:
    file_df = pd.read_csv(file_,sep=',', parse_dates=[0], infer_datetime_format=True,header=None,skiprows=1 )
    file_df['model'] = file_
    df = df.append(file_df)

In [ ]:
df.columns =['class', 'precision', 'recall', 'f1','support','model']

In [ ]:
def get_filename(path):
    temp_str = path.split('/')
    return temp_str[-1]

In [ ]:
df["model"] = df["model"].apply(get_filename)

In [ ]:
# saving concat data to csv
df.to_csv("/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/totalG.csv",index=False)

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/DBDA_PROJECT/Gaussian_clf/totalAG.csv")

In [ ]:
df

,class,accuracy,precision,recall,f1,support,model
0,0,100.000000,0.995736,1.000000,0.997863,467,balanced_SMOTE_CNN.csv
1,1,96.642686,0.971084,0.966427,0.968750,417,balanced_SMOTE_CNN.csv
2,2,99.350649,0.997826,0.993506,0.995662,462,balanced_SMOTE_CNN.csv
3,3,99.541284,1.000000,0.995413,0.997701,436,balanced_SMOTE_CNN.csv
4,4,100.000000,0.995662,1.000000,0.997826,459,balanced_SMOTE_CNN.csv
...,...,...,...,...,...,...,...
511,38,88.440860,0.987988,0.884409,0.933333,372,imbalanced_resnet_L50.csv
512,39,70.454545,1.000000,0.704545,0.826667,88,imbalanced_resnet_L50.csv
513,40,96.273292,0.971787,0.962733,0.967239,322,imbalanced_resnet_L50.csv
514,41,95.925926,0.955720,0.959259,0.957486,270,imbalanced_resnet_L50.csv
515,42,93.928571,1.000000,0.939286,0.968692,280,imbalanced_resnet_L50.csv

In [ ]:
df['total'] = df['accuracy']+df['precision'] + df['recall'] + df['f1']

In [ ]:
df.total = df.total.round(4)

In [ ]:
z=df.groupby('class',sort=False)['total'].max()
z

class
0     103.0000
1     101.2128
2     102.7654
3     102.9830
4     102.9967
5     102.9931
6     103.0000
7     103.0000
8     103.0000
9     103.0000
10    102.5428
11    103.0000
12    101.8489
13    102.9756
14    102.9872
15    103.0000
16    102.7872
17    103.0000
18    102.7753
19    102.7745
20    103.0000
21    102.7645
22    103.0000
23    101.2292
24    102.7907
25    102.7734
26    103.0000
27    103.0000
28    103.0000
29    103.0000
30    103.0000
31    103.0000
32    103.0000
33    103.0000
34    102.4120
35    103.0000
36    103.0000
37    103.0000
38    101.0461
39    103.0000
40    101.4145
41    102.5648
42    102.5564
Name: total, dtype: float64

In [ ]:
df0=df[(df['class']==0) & (df['total']==df['total'].max())].iloc[:,0:8]
df0

,class,accuracy,precision,recall,f1,support,model
258,0,100.0,1.0,1.0,1.0,36,balanced_wt_ResNet_50.csv

In [ ]:
df1=df[(df['class']==1) & (df['total']==z[1].max())].iloc[:,0:8]
df1

,class,accuracy,precision,recall,f1,support,model,total
44,1,98.321343,0.9447,0.983213,0.963572,417,balanced_SMOTE_ResNet_50.csv,101.2128

In [ ]:
df2=df[(df['class']==2) & (df['total']==z[2].max())].iloc[:,0:8]
df2

,class,accuracy,precision,recall,f1,support,model,total
260,2,99.77221,0.997722,0.997722,0.997722,439,balanced_wt_ResNet_50.csv,102.7654

In [ ]:
df3=df[(df['class']==3) & (df['total']==z[3].max())].iloc[:,0:8]
df3

,class,accuracy,precision,recall,f1,support,model,total
89,3,100.0,0.988662,1.0,0.994299,436,balanced_SMOTE_ResNet_152.csv,102.983

In [ ]:
df4=df[(df['class']==4) & (df['total']==z[4].max())].iloc[:,0:8]
df4

,class,accuracy,precision,recall,f1,support,model,total
90,4,100.0,0.997826,1.0,0.998912,459,balanced_SMOTE_ResNet_152.csv,102.9967

In [ ]:
df5=df[(df['class']==5) & (df['total']==z[5].max())].iloc[:,0:8]
df5

,class,accuracy,precision,recall,f1,support,model,total
306,5,100.0,0.995392,1.0,0.997691,432,balanced_wt_ResNet_152.csv,102.9931

In [ ]:
df6=df[(df['class']==6) & (df['total']==z[6].max())].iloc[:,0:8]
df6

,class,accuracy,precision,recall,f1,support,model,total
350,6,100.0,1.0,1.0,1.0,162,imbalanced_cnn.csv,103.0

In [ ]:
df7=df[(df['class']==7) & (df['total']==z[7].max())].iloc[:,0:8]
df7

,class,accuracy,precision,recall,f1,support,model,total
93,7,100.0,1.0,1.0,1.0,500,balanced_SMOTE_ResNet_152.csv,103.0

In [ ]:
df8=df[(df['class']==8) & (df['total']==z[8].max())].iloc[:,0:8]
df8

,class,accuracy,precision,recall,f1,support,model,total
223,8,100.0,1.0,1.0,1.0,88,balanced_tk_ResNet50_152.csv,103.0
266,8,100.0,1.0,1.0,1.0,81,balanced_wt_ResNet_50.csv,103.0
309,8,100.0,1.0,1.0,1.0,81,balanced_wt_ResNet_152.csv,103.0

In [ ]:
df9=df[(df['class']==1) & (df['total']==z[9].max())].iloc[:,0:8]
df9

Empty DataFrame
Columns: [class, accuracy, precision, recall, f1, support, model, total]
Index: []

In [ ]:
df10=df[(df['class']==10) & (df['total']==z[10].max())].iloc[:,0:8]
df10

,class,accuracy,precision,recall,f1,support,model,total
96,10,99.54955,1.0,0.995495,0.997743,444,balanced_SMOTE_ResNet_152.csv,102.5428

In [ ]:
df11=df[(df['class']==11) & (df['total']==z[11].max())].iloc[:,0:8]
df11

,class,accuracy,precision,recall,f1,support,model,total
54,11,100.0,1.0,1.0,1.0,438,balanced_SMOTE_ResNet_50.csv,103.0

In [ ]:
df12=df[(df['class']==12) & (df['total']==z[12].max())].iloc[:,0:8]
df12

,class,accuracy,precision,recall,f1,support,model,total
55,12,98.979592,0.92381,0.989796,0.955665,392,balanced_SMOTE_ResNet_50.csv,101.8489

In [ ]:
df13=df[(df['class']==13) & (df['total']==z[13].max())].iloc[:,0:8]
df13

,class,accuracy,precision,recall,f1,support,model,total
56,13,100.0,0.983796,1.0,0.991832,425,balanced_SMOTE_ResNet_50.csv,102.9756

In [ ]:
df14=df[(df['class']==14) & (df['total']==z[14].max())].iloc[:,0:8]
df14

,class,accuracy,precision,recall,f1,support,model,total
100,14,100.0,0.991489,1.0,0.995726,466,balanced_SMOTE_ResNet_152.csv,102.9872

In [ ]:
df15=df[(df['class']==15) & (df['total']==z[15].max())].iloc[:,0:8]
df15

,class,accuracy,precision,recall,f1,support,model,total
15,15,100.0,1.0,1.0,1.0,449,balanced_SMOTE_CNN.csv,103.0
101,15,100.0,1.0,1.0,1.0,449,balanced_SMOTE_ResNet_152.csv,103.0
316,15,100.0,1.0,1.0,1.0,82,balanced_wt_ResNet_152.csv,103.0

In [ ]:
df16=df[(df['class']==16) & (df['total']==z[16].max())].iloc[:,0:8]
df16

,class,accuracy,precision,recall,f1,support,model,total
102,16,99.793388,0.997934,0.997934,0.997934,484,balanced_SMOTE_ResNet_152.csv,102.7872

In [ ]:
df17=df[(df['class']==17) & (df['total']==z[17].max())].iloc[:,0:8]
df17

,class,accuracy,precision,recall,f1,support,model,total
17,17,100.0,1.0,1.0,1.0,445,balanced_SMOTE_CNN.csv,103.0
60,17,100.0,1.0,1.0,1.0,445,balanced_SMOTE_ResNet_50.csv,103.0
275,17,100.0,1.0,1.0,1.0,53,balanced_wt_ResNet_50.csv,103.0

In [ ]:
df18=df[(df['class']==18) & (df['total']==z[18].max())].iloc[:,0:8]
df18

,class,accuracy,precision,recall,f1,support,model,total
18,18,99.784946,0.995708,0.997849,0.996778,465,balanced_SMOTE_CNN.csv,102.7753

In [ ]:
df19=df[(df['class']==19) & (df['total']==z[19].max())].iloc[:,0:8]
df19

,class,accuracy,precision,recall,f1,support,model,total
105,19,99.787234,0.993644,0.997872,0.995754,470,balanced_SMOTE_ResNet_152.csv,102.7745

In [ ]:
df20=df[(df['class']==20) & (df['total']==z[20].max())].iloc[:,0:8]
df20

,class,accuracy,precision,recall,f1,support,model,total
278,20,100.0,1.0,1.0,1.0,47,balanced_wt_ResNet_50.csv,103.0

In [ ]:
df21=df[(df['class']==21) & (df['total']==z[21].max())].iloc[:,0:8]
df21

,class,accuracy,precision,recall,f1,support,model,total
21,21,99.767981,1.0,0.99768,0.998839,431,balanced_SMOTE_CNN.csv,102.7645

In [ ]:
df22=df[(df['class']==22) & (df['total']==z[22].max())].iloc[:,0:8]
df22

,class,accuracy,precision,recall,f1,support,model,total
65,22,100.0,1.0,1.0,1.0,425,balanced_SMOTE_ResNet_50.csv,103.0

In [ ]:
df23=df[(df['class']==23) & (df['total']==z[23].max())].iloc[:,0:8]
df23

,class,accuracy,precision,recall,f1,support,model,total
281,23,98.275862,0.986159,0.982759,0.984456,290,balanced_wt_ResNet_50.csv,101.2292

In [ ]:
df24=df[(df['class']==24) & (df['total']==z[24].max())].iloc[:,0:8]
df24

,class,accuracy,precision,recall,f1,support,model,total
24,24,99.793814,1.0,0.997938,0.998968,485,balanced_SMOTE_CNN.csv,102.7907

In [ ]:
df25=df[(df['class']==25) & (df['total']==z[25].max())].iloc[:,0:8]
df25

,class,accuracy,precision,recall,f1,support,model,total
25,25,99.776786,1.0,0.997768,0.998883,448,balanced_SMOTE_CNN.csv,102.7734

In [ ]:
df26=df[(df['class']==26) & (df['total']==z[26].max())].iloc[:,0:8]
df26

,class,accuracy,precision,recall,f1,support,model,total
26,26,100.0,1.0,1.0,1.0,442,balanced_SMOTE_CNN.csv,103.0
284,26,100.0,1.0,1.0,1.0,40,balanced_wt_ResNet_50.csv,103.0

In [ ]:
df27=df[(df['class']==27) & (df['total']==z[27].max())].iloc[:,0:8]
df27

,class,accuracy,precision,recall,f1,support,model,total
27,27,100.0,1.0,1.0,1.0,445,balanced_SMOTE_CNN.csv,103.0
113,27,100.0,1.0,1.0,1.0,445,balanced_SMOTE_ResNet_152.csv,103.0

In [ ]:
df28=df[(df['class']==28) & (df['total']==z[28].max())].iloc[:,0:8]
df28

,class,accuracy,precision,recall,f1,support,model,total
28,28,100.0,1.0,1.0,1.0,470,balanced_SMOTE_CNN.csv,103.0
114,28,100.0,1.0,1.0,1.0,470,balanced_SMOTE_ResNet_152.csv,103.0
286,28,100.0,1.0,1.0,1.0,83,balanced_wt_ResNet_50.csv,103.0
329,28,100.0,1.0,1.0,1.0,83,balanced_wt_ResNet_152.csv,103.0

In [ ]:
df29=df[(df['class']==29) & (df['total']==z[29].max())].iloc[:,0:8]
df29

,class,accuracy,precision,recall,f1,support,model,total
29,29,100.0,1.0,1.0,1.0,480,balanced_SMOTE_CNN.csv,103.0
115,29,100.0,1.0,1.0,1.0,480,balanced_SMOTE_ResNet_152.csv,103.0

In [ ]:
df30=df[(df['class']==30) & (df['total']==z[30].max())].iloc[:,0:8]
df30

,class,accuracy,precision,recall,f1,support,model,total
30,30,100.0,1.0,1.0,1.0,441,balanced_SMOTE_CNN.csv,103.0
116,30,100.0,1.0,1.0,1.0,441,balanced_SMOTE_ResNet_152.csv,103.0
417,30,100.0,1.0,1.0,1.0,62,balanced_WT_cnn.csv,103.0

In [ ]:
df31=df[(df['class']==31) & (df['total']==z[31].max())].iloc[:,0:8]
df31

,class,accuracy,precision,recall,f1,support,model,total
31,31,100.0,1.0,1.0,1.0,456,balanced_SMOTE_CNN.csv,103.0
74,31,100.0,1.0,1.0,1.0,456,balanced_SMOTE_ResNet_50.csv,103.0
117,31,100.0,1.0,1.0,1.0,456,balanced_SMOTE_ResNet_152.csv,103.0
289,31,100.0,1.0,1.0,1.0,47,balanced_wt_ResNet_50.csv,103.0
332,31,100.0,1.0,1.0,1.0,47,balanced_wt_ResNet_152.csv,103.0
418,31,100.0,1.0,1.0,1.0,47,balanced_WT_cnn.csv,103.0

In [ ]:
df32=df[(df['class']==32) & (df['total']==z[32].max())].iloc[:,0:8]
df32

,class,accuracy,precision,recall,f1,support,model,total
118,32,100.0,1.0,1.0,1.0,458,balanced_SMOTE_ResNet_152.csv,103.0
290,32,100.0,1.0,1.0,1.0,399,balanced_wt_ResNet_50.csv,103.0

In [ ]:
df33=df[(df['class']==33) & (df['total']==z[33].max())].iloc[:,0:8]
df33

,class,accuracy,precision,recall,f1,support,model,total
33,33,100.0,1.0,1.0,1.0,471,balanced_SMOTE_CNN.csv,103.0
119,33,100.0,1.0,1.0,1.0,471,balanced_SMOTE_ResNet_152.csv,103.0
162,33,100.0,1.0,1.0,1.0,56,balanced_tk_cnn.csv,103.0
291,33,100.0,1.0,1.0,1.0,68,balanced_wt_ResNet_50.csv,103.0
334,33,100.0,1.0,1.0,1.0,68,balanced_wt_ResNet_152.csv,103.0
377,33,100.0,1.0,1.0,1.0,68,imbalanced_cnn.csv,103.0
420,33,100.0,1.0,1.0,1.0,68,balanced_WT_cnn.csv,103.0

In [ ]:
df34=df[(df['class']==34) & (df['total']==z[34].max())].iloc[:,0:8]
df34

,class,accuracy,precision,recall,f1,support,model,total
206,34,99.489796,0.953545,0.994898,0.973783,392,balanced_tk_ResNet50_50.csv,102.412

In [ ]:
df35=df[(df['class']==35) & (df['total']==z[35].max())].iloc[:,0:8]
df35

,class,accuracy,precision,recall,f1,support,model,total
78,35,100.0,1.0,1.0,1.0,420,balanced_SMOTE_ResNet_50.csv,103.0
121,35,100.0,1.0,1.0,1.0,420,balanced_SMOTE_ResNet_152.csv,103.0
293,35,100.0,1.0,1.0,1.0,79,balanced_wt_ResNet_50.csv,103.0
336,35,100.0,1.0,1.0,1.0,79,balanced_wt_ResNet_152.csv,103.0
508,35,100.0,1.0,1.0,1.0,79,imbalanced_resnet_L50.csv,103.0

In [ ]:
df36=df[(df['class']==36) & (df['total']==z[36].max())].iloc[:,0:8]
df36

,class,accuracy,precision,recall,f1,support,model,total
36,36,100.0,1.0,1.0,1.0,427,balanced_SMOTE_CNN.csv,103.0
122,36,100.0,1.0,1.0,1.0,427,balanced_SMOTE_ResNet_152.csv,103.0
165,36,100.0,1.0,1.0,1.0,43,balanced_tk_cnn.csv,103.0
337,36,100.0,1.0,1.0,1.0,49,balanced_wt_ResNet_152.csv,103.0
380,36,100.0,1.0,1.0,1.0,49,imbalanced_cnn.csv,103.0

In [ ]:
df37=df[(df['class']==37) & (df['total']==z[37].max())].iloc[:,0:8]
df37

,class,accuracy,precision,recall,f1,support,model,total
37,37,100.0,1.0,1.0,1.0,439,balanced_SMOTE_CNN.csv,103.0
295,37,100.0,1.0,1.0,1.0,44,balanced_wt_ResNet_50.csv,103.0
338,37,100.0,1.0,1.0,1.0,44,balanced_wt_ResNet_152.csv,103.0
381,37,100.0,1.0,1.0,1.0,44,imbalanced_cnn.csv,103.0

In [ ]:
df38=df[(df['class']==38) & (df['total']==z[38].max())].iloc[:,0:8]
df38

,class,accuracy,precision,recall,f1,support,model,total
296,38,98.11828,0.970745,0.981183,0.975936,372,balanced_wt_ResNet_50.csv,101.0461

In [ ]:
df39=df[(df['class']==39) & (df['total']==z[39].max())].iloc[:,0:8]
df39

,class,accuracy,precision,recall,f1,support,model,total
39,39,100.0,1.0,1.0,1.0,416,balanced_SMOTE_CNN.csv,103.0
125,39,100.0,1.0,1.0,1.0,416,balanced_SMOTE_ResNet_152.csv,103.0
297,39,100.0,1.0,1.0,1.0,88,balanced_wt_ResNet_50.csv,103.0
340,39,100.0,1.0,1.0,1.0,88,balanced_wt_ResNet_152.csv,103.0
426,39,100.0,1.0,1.0,1.0,88,balanced_WT_cnn.csv,103.0

In [ ]:
df40=df[(df['class']==40) & (df['total']==z[40].max())].iloc[:,0:8]
df40

,class,accuracy,precision,recall,f1,support,model,total
298,40,98.447205,0.99373,0.984472,0.98908,322,balanced_wt_ResNet_50.csv,101.4145

In [ ]:
df41=df[(df['class']==41) & (df['total']==z[41].max())].iloc[:,0:8]
df41

,class,accuracy,precision,recall,f1,support,model,total
299,41,99.62963,0.960714,0.996296,0.978182,270,balanced_wt_ResNet_50.csv,102.5648

In [ ]:
df42=df[(df['class']==42) & (df['total']==z[42].max())].iloc[:,0:8]
df42

,class,accuracy,precision,recall,f1,support,model,total
42,42,99.566161,0.997826,0.995662,0.996743,461,balanced_SMOTE_CNN.csv,102.5564

In [ ]:
df_list=[df,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23,df24,df25,df26,df27,df28,df29,df30,df31,df32,df33,df34,df35,df36,df37,df38,df39,df40,df41,df42]

In [ ]:
model_df=pd.concat([df0,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23,df24,df25,df26,df27,df28,df29,df30,df31,df32,df33,df34,df35,df36,df37,df38,df39,df40,df41,df42], sort=False)

In [ ]:
model_df

,class,accuracy,precision,recall,f1,support,model,total
258,0,100.000000,1.000000,1.000000,1.000000,36,balanced_wt_ResNet_50.csv,NaN
44,1,98.321343,0.944700,0.983213,0.963572,417,balanced_SMOTE_ResNet_50.csv,101.2128
260,2,99.772210,0.997722,0.997722,0.997722,439,balanced_wt_ResNet_50.csv,102.7654
89,3,100.000000,0.988662,1.000000,0.994299,436,balanced_SMOTE_ResNet_152.csv,102.9830
90,4,100.000000,0.997826,1.000000,0.998912,459,balanced_SMOTE_ResNet_152.csv,102.9967
...,...,...,...,...,...,...,...,...
340,39,100.000000,1.000000,1.000000,1.000000,88,balanced_wt_ResNet_152.csv,103.0000
426,39,100.000000,1.000000,1.000000,1.000000,88,balanced_WT_cnn.csv,103.0000
298,40,98.447205,0.993730,0.984472,0.989080,322,balanced_wt_ResNet_50.csv,101.4145
299,41,99.629630,0.960714,0.996296,0.978182,270,balanced_wt_ResNet_50.csv,102.5648
42,42,99.566161,0.997826,0.995662,0.996743,461,balanced_SMOTE_CNN.csv,102.5564

In [ ]:
print(model_df.to_string())

     class    accuracy  precision    recall        f1  support                          model     total
258      0  100.000000   1.000000  1.000000  1.000000       36      balanced_wt_ResNet_50.csv       NaN
44       1   98.321343   0.944700  0.983213  0.963572      417   balanced_SMOTE_ResNet_50.csv  101.2128
260      2   99.772210   0.997722  0.997722  0.997722      439      balanced_wt_ResNet_50.csv  102.7654
89       3  100.000000   0.988662  1.000000  0.994299      436  balanced_SMOTE_ResNet_152.csv  102.9830
90       4  100.000000   0.997826  1.000000  0.998912      459  balanced_SMOTE_ResNet_152.csv  102.9967
306      5  100.000000   0.995392  1.000000  0.997691      432     balanced_wt_ResNet_152.csv  102.9931
350      6  100.000000   1.000000  1.000000  1.000000      162             imbalanced_cnn.csv  103.0000
93       7  100.000000   1.000000  1.000000  1.000000      500  balanced_SMOTE_ResNet_152.csv  103.0000
223      8  100.000000   1.000000  1.000000  1.000000       88   balanced_tk_ResNet50_152.csv  103.0000
266      8  100.000000   1.000000  1.000000  1.000000       81      balanced_wt_ResNet_50.csv  103.0000
309      8  100.000000   1.000000  1.000000  1.000000       81     balanced_wt_ResNet_152.csv  103.0000
96      10   99.549550   1.000000  0.995495  0.997743      444  balanced_SMOTE_ResNet_152.csv  102.5428
54      11  100.000000   1.000000  1.000000  1.000000      438   balanced_SMOTE_ResNet_50.csv  103.0000
55      12   98.979592   0.923810  0.989796  0.955665      392   balanced_SMOTE_ResNet_50.csv  101.8489
56      13  100.000000   0.983796  1.000000  0.991832      425   balanced_SMOTE_ResNet_50.csv  102.9756
100     14  100.000000   0.991489  1.000000  0.995726      466  balanced_SMOTE_ResNet_152.csv  102.9872
15      15  100.000000   1.000000  1.000000  1.000000      449         balanced_SMOTE_CNN.csv  103.0000
101     15  100.000000   1.000000  1.000000  1.000000      449  balanced_SMOTE_ResNet_152.csv  103.0000
316     15  100.000000   1.000000  1.000000  1.000000       82     balanced_wt_ResNet_152.csv  103.0000
102     16   99.793388   0.997934  0.997934  0.997934      484  balanced_SMOTE_ResNet_152.csv  102.7872
17      17  100.000000   1.000000  1.000000  1.000000      445         balanced_SMOTE_CNN.csv  103.0000
60      17  100.000000   1.000000  1.000000  1.000000      445   balanced_SMOTE_ResNet_50.csv  103.0000
275     17  100.000000   1.000000  1.000000  1.000000       53      balanced_wt_ResNet_50.csv  103.0000
18      18   99.784946   0.995708  0.997849  0.996778      465         balanced_SMOTE_CNN.csv  102.7753
105     19   99.787234   0.993644  0.997872  0.995754      470  balanced_SMOTE_ResNet_152.csv  102.7745
278     20  100.000000   1.000000  1.000000  1.000000       47      balanced_wt_ResNet_50.csv  103.0000
21      21   99.767981   1.000000  0.997680  0.998839      431         balanced_SMOTE_CNN.csv  102.7645
65      22  100.000000   1.000000  1.000000  1.000000      425   balanced_SMOTE_ResNet_50.csv  103.0000
281     23   98.275862   0.986159  0.982759  0.984456      290      balanced_wt_ResNet_50.csv  101.2292
24      24   99.793814   1.000000  0.997938  0.998968      485         balanced_SMOTE_CNN.csv  102.7907
25      25   99.776786   1.000000  0.997768  0.998883      448         balanced_SMOTE_CNN.csv  102.7734
26      26  100.000000   1.000000  1.000000  1.000000      442         balanced_SMOTE_CNN.csv  103.0000
284     26  100.000000   1.000000  1.000000  1.000000       40      balanced_wt_ResNet_50.csv  103.0000
27      27  100.000000   1.000000  1.000000  1.000000      445         balanced_SMOTE_CNN.csv  103.0000
113     27  100.000000   1.000000  1.000000  1.000000      445  balanced_SMOTE_ResNet_152.csv  103.0000
28      28  100.000000   1.000000  1.000000  1.000000      470         balanced_SMOTE_CNN.csv  103.0000
114     28  100.000000   1.000000  1.000000  1.000000      470  balanced_SMOTE_ResNet_152.csv  103.0000
286     28  100.000000   1.000000  1.000000  1.000000       83      balanced_wt_ResNet_50.csv  103.0000
329     28  100.000000   1.000000  1.000000  1.000000       83     balanced_wt_ResNet_152.csv  103.0000
29      29  100.000000   1.000000  1.000000  1.000000      480         balanced_SMOTE_CNN.csv  103.0000
115     29  100.000000   1.000000  1.000000  1.000000      480  balanced_SMOTE_ResNet_152.csv  103.0000
30      30  100.000000   1.000000  1.000000  1.000000      441         balanced_SMOTE_CNN.csv  103.0000
116     30  100.000000   1.000000  1.000000  1.000000      441  balanced_SMOTE_ResNet_152.csv  103.0000
417     30  100.000000   1.000000  1.000000  1.000000       62            balanced_WT_cnn.csv  103.0000
31      31  100.000000   1.000000  1.000000  1.000000      456         balanced_SMOTE_CNN.csv  103.0000
74      31  100.000000   1.000000  1.000000  1.000000      456   balanced_SMOTE_ResNet_50.csv  103.0000
117     31  100.000000   1.000000  1.000000  1.000000      456  balanced_SMOTE_ResNet_152.csv  103.0000
289     31  100.000000   1.000000  1.000000  1.000000       47      balanced_wt_ResNet_50.csv  103.0000
332     31  100.000000   1.000000  1.000000  1.000000       47     balanced_wt_ResNet_152.csv  103.0000
418     31  100.000000   1.000000  1.000000  1.000000       47            balanced_WT_cnn.csv  103.0000
118     32  100.000000   1.000000  1.000000  1.000000      458  balanced_SMOTE_ResNet_152.csv  103.0000
290     32  100.000000   1.000000  1.000000  1.000000      399      balanced_wt_ResNet_50.csv  103.0000
33      33  100.000000   1.000000  1.000000  1.000000      471         balanced_SMOTE_CNN.csv  103.0000
119     33  100.000000   1.000000  1.000000  1.000000      471  balanced_SMOTE_ResNet_152.csv  103.0000
162     33  100.000000   1.000000  1.000000  1.000000       56            balanced_tk_cnn.csv  103.0000
291     33  100.000000   1.000000  1.000000  1.000000       68      balanced_wt_ResNet_50.csv  103.0000
334     33  100.000000   1.000000  1.000000  1.000000       68     balanced_wt_ResNet_152.csv  103.0000
377     33  100.000000   1.000000  1.000000  1.000000       68             imbalanced_cnn.csv  103.0000
420     33  100.000000   1.000000  1.000000  1.000000       68            balanced_WT_cnn.csv  103.0000
206     34   99.489796   0.953545  0.994898  0.973783      392    balanced_tk_ResNet50_50.csv  102.4120
78      35  100.000000   1.000000  1.000000  1.000000      420   balanced_SMOTE_ResNet_50.csv  103.0000
121     35  100.000000   1.000000  1.000000  1.000000      420  balanced_SMOTE_ResNet_152.csv  103.0000
293     35  100.000000   1.000000  1.000000  1.000000       79      balanced_wt_ResNet_50.csv  103.0000
336     35  100.000000   1.000000  1.000000  1.000000       79     balanced_wt_ResNet_152.csv  103.0000
508     35  100.000000   1.000000  1.000000  1.000000       79      imbalanced_resnet_L50.csv  103.0000
36      36  100.000000   1.000000  1.000000  1.000000      427         balanced_SMOTE_CNN.csv  103.0000
122     36  100.000000   1.000000  1.000000  1.000000      427  balanced_SMOTE_ResNet_152.csv  103.0000
165     36  100.000000   1.000000  1.000000  1.000000       43            balanced_tk_cnn.csv  103.0000
337     36  100.000000   1.000000  1.000000  1.000000       49     balanced_wt_ResNet_152.csv  103.0000
380     36  100.000000   1.000000  1.000000  1.000000       49             imbalanced_cnn.csv  103.0000
37      37  100.000000   1.000000  1.000000  1.000000      439         balanced_SMOTE_CNN.csv  103.0000
295     37  100.000000   1.000000  1.000000  1.000000       44      balanced_wt_ResNet_50.csv  103.0000
338     37  100.000000   1.000000  1.000000  1.000000       44     balanced_wt_ResNet_152.csv  103.0000
381     37  100.000000   1.000000  1.000000  1.000000       44             imbalanced_cnn.csv  103.0000
296     38   98.118280   0.970745  0.981183  0.975936      372      balanced_wt_ResNet_50.csv  101.0461
39      39  100.000000   1.000000  1.000000  1.000000      416         balanced_SMOTE_CNN.csv  103.0000
125     39  100.000000   1.000000  1.000000  1.000000      416  balanced_SMOTE_ResNet_152.csv  103.0000
297     39  100.000000   1.000000  1.000000  1.000000       88      balanced_wt_ResNet_50.csv  103.0000
340     39  100.000000   1.000000  1.000000  1.000000       88     balanced_wt_ResNet_152.csv  103.0000
426     39  100.000000   1.000000  1.000000  1.000000       88            balanced_WT_cnn.csv  103.0000
298     40   98.447205   0.993730  0.984472  0.989080      322      balanced_wt_ResNet_50.csv  101.4145
299     41   99.629630   0.960714  0.996296  0.978182      270      balanced_wt_ResNet_50.csv  102.5648
42      42   99.566161   0.997826  0.995662  0.996743      461         balanced_SMOTE_CNN.csv  102.5564

In [ ]:
model_df.model.value_counts()

balanced_SMOTE_ResNet_152.csv    18
balanced_wt_ResNet_50.csv        17
balanced_SMOTE_CNN.csv           17
balanced_wt_ResNet_152.csv       10
balanced_SMOTE_ResNet_50.csv      8
imbalanced_cnn.csv                4
balanced_WT_cnn.csv               4
balanced_tk_cnn.csv               2
balanced_tk_ResNet50_152.csv      1
balanced_tk_ResNet50_50.csv       1
imbalanced_resnet_L50.csv         1
Name: model, dtype: int64